---
- name: Update user
  become: true
  ansible.builtin.user:
    name: "{{ devbox_user.login }}"
    comment: Kirill Abrosimov
    shell: "/opt/homebrew/bin/fish" # TODO: can we get path to the shell accordingly to OS?
    create_home: false
    update_password: on_create
    generate_ssh_key: true
    ssh_key_type: "ed25519"
    ssh_key_passphrase: "{{ devbox_user.ssh_pass_phrase }}"
