---
- name: Find a shell path
  ansible.builtin.command: "command -v fish"
  register: shell_path
  changed_when: false
  failed_when: shell_path.rc != 0

- name: Fail early if shell not found
  ansible.builtin.assert:
    that:
      - shell_path.stdout | length > 0
    fail_msg: "Shell not found in PATH even after installation!"

- name: Update user
  become: true
  ansible.builtin.user:
    name: "{{ devbox_user.login }}"
    comment: Kirill Abrosimov
    shell: "{{ shell_path.stdout }}"
    create_home: false
    update_password: on_create
    generate_ssh_key: true
    ssh_key_type: "ed25519"
    ssh_key_passphrase: "{{ devbox_user.ssh_pass_phrase }}"
