#!/usr/bin/env bash
# Generate a per-profile git identity into the (gitignored) local overlay and,
# unless DEV=1, apply it to the live ~/.config/git/ immediately.
#
# The identity is intentionally NOT stored in vault: it is regenerable in three
# prompts and the signing key it references is backed up separately. The local
# overlay is the source of truth (deployed by install_configs.yml Block 6); this
# script also copies straight to $HOME so a standalone `make git-identity` takes
# effect without a full playbook run.
#
# What lands in the identity file (per profile):
#   [user] name / email / signingkey
#   [gpg]  format = ssh          (only if signing key given)
#   [commit] gpgsign = true      (only if signing key given)
#   [tag]  gpgSign = true        (only if signing key given)
#   [init] defaultBranch         (personal → master, work → main by default)
#   [jira] keyPosition = suffix  (work only — personal branches lack Jira keys)
#
# Usage: git-identity-gen.sh <personal|work>
set -euo pipefail

profile="${1:-}"
case "$profile" in
    personal|work) ;;
    *) echo "usage: git-identity-gen.sh <personal|work>" >&2; exit 2 ;;
esac

# Per-profile defaults. Override on the prompt if you want something else.
case "$profile" in
    personal) default_branch_default="master" ;;
    work)     default_branch_default="main" ;;
esac

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src="$repo_root/roles/devbox/local/.config/git/identity-${profile}.gitconfig"
mkdir -p "$(dirname "$src")"

if [ -f "$src" ]; then
    echo "Existing identity for '$profile':"
    sed 's/^/  /' "$src"
    read -rp "Overwrite? [y/N]: " ans
    case "$ans" in y|Y|yes) ;; *) echo "Kept existing."; exit 0 ;; esac
fi

# Pre-populate prompt defaults from an existing ~/.gitconfig if present. The
# sanitize task in the playbook archives that file into ~/.gitconfig.bak.<ts>
# on the same run, so on first bootstrap the user just hits Enter four times.
# On subsequent runs (no ~/.gitconfig) prompts default to empty / profile.
default_name=""
default_email=""
default_signkey=""
default_branch_from_config=""
if [ -f "$HOME/.gitconfig" ]; then
    default_name=$(git config --file "$HOME/.gitconfig" --get user.name 2>/dev/null || true)
    default_email=$(git config --file "$HOME/.gitconfig" --get user.email 2>/dev/null || true)
    default_signkey=$(git config --file "$HOME/.gitconfig" --get user.signingkey 2>/dev/null || true)
    default_branch_from_config=$(git config --file "$HOME/.gitconfig" --get init.defaultBranch 2>/dev/null || true)
    # Strip surrounding double-quotes that some setups leave in the file
    # (e.g. `name = "Kirill Abrosimov"` — git accepts both forms).
    default_name=${default_name#\"}; default_name=${default_name%\"}
    default_email=${default_email#\"}; default_email=${default_email%\"}
fi
[ -n "$default_branch_from_config" ] && default_branch_default="$default_branch_from_config"

# Helper: read with a default value shown in [brackets]; Enter accepts the default.
read_with_default() {
    local prompt="$1" default="$2" var
    if [ -n "$default" ]; then
        read -rp "$prompt [$default]: " var
        printf '%s' "${var:-$default}"
    else
        read -rp "$prompt: " var
        printf '%s' "$var"
    fi
}

name=$(read_with_default "[$profile] git user.name" "$default_name")
email=$(read_with_default "[$profile] git user.email" "$default_email")
signkey=$(read_with_default "[$profile] sign commits? SSH public-key path (empty = no signing)" "$default_signkey")
default_branch=$(read_with_default "[$profile] init.defaultBranch" "$default_branch_default")

{
    echo "# Generated by 'make git-identity' for the '$profile' profile."
    echo "# Local overlay — gitignored, per-machine. Regenerate with make git-identity."
    echo "[user]"
    echo "	name = $name"
    echo "	email = $email"
    if [ -n "$signkey" ]; then
        echo "	signingkey = $signkey"
        echo "[gpg]"
        echo "	format = ssh"
        echo "[commit]"
        echo "	gpgsign = true"
        echo "[tag]"
        echo "	gpgSign = true"
    fi
    echo "[init]"
    echo "	defaultBranch = $default_branch"
    if [ "$profile" = "work" ]; then
        echo "[jira]"
        echo "	keyPosition = suffix"
    fi
} > "$src"
echo "Wrote source: $src"

# Immediate apply to the live HOME, unless building the debug tree (dev_mode).
if [ "${DEV:-}" != "1" ]; then
    dst="$HOME/.config/git/identity-${profile}.gitconfig"
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "Applied: $dst"
fi
