#!/usr/bin/env python3
# Generate a per-profile git identity into the (gitignored) local overlay and,
# unless DEV=1, apply it to the live ~/.config/git/ immediately.
#
# The identity is intentionally NOT stored in vault: it is regenerable in three
# prompts and the signing key it references is backed up separately. The local
# overlay is the source of truth (deployed by install_configs.yml Block 6); this
# script also copies straight to $HOME so a standalone `make git-identity` takes
# effect without a full playbook run.
#
# What lands in the identity file (per profile):
#   [user] name / email / signingkey
#   [gpg]  format = ssh          (only if signing key given)
#   [commit] gpgsign = true      (only if signing key given)
#   [tag]  gpgSign = true        (only if signing key given)
#   [init] defaultBranch         (personal → master, work → main by default)
#   [jira] keyPosition = suffix  (work only — personal branches lack Jira keys)
#
# Self-contained, standard library only — invoked as a plain script from the
# Makefile (`make git-identity`). Tests: tests/scripts/.
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

VALID_PROFILES = ("personal", "work")
PROFILE_DEFAULT_BRANCH = {"personal": "master", "work": "main"}
USAGE = "usage: git-identity-gen.py <personal|work>"


def parse_profile(argv: list[str]) -> str:
    if len(argv) < 2 or argv[1] not in VALID_PROFILES:
        print(USAGE, file=sys.stderr)
        raise SystemExit(2)
    return argv[1]


def _git_config_get(gitconfig: Path, key: str) -> str:
    result = subprocess.run(
        ["git", "config", "--file", str(gitconfig), "--get", key],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def strip_one_pair_of_quotes(value: str) -> str:
    # git accepts `name = "Foo"` and stores it literally; identity file is unquoted.
    return value.removeprefix('"').removesuffix('"')


def read_gitconfig_defaults(gitconfig: Path) -> dict[str, str]:
    if not gitconfig.is_file():
        return {}
    name = strip_one_pair_of_quotes(_git_config_get(gitconfig, "user.name"))
    email = strip_one_pair_of_quotes(_git_config_get(gitconfig, "user.email"))
    signkey = _git_config_get(gitconfig, "user.signingkey")
    default_branch = _git_config_get(gitconfig, "init.defaultBranch")
    return {
        "name": name,
        "email": email,
        "signkey": signkey,
        "default_branch": default_branch,
    }


def prompt_with_default(label: str, default: str) -> str:
    prompt = f"{label} [{default}]: " if default else f"{label}: "
    value = input(prompt)
    return value or default


def render_identity(
    *,
    profile: str,
    name: str,
    email: str,
    signkey: str,
    default_branch: str,
) -> str:
    lines = [
        f"# Generated by 'make git-identity' for the '{profile}' profile.",
        "# Local overlay — gitignored, per-machine. Regenerate with make git-identity.",
        "[user]",
        f"\tname = {name}",
        f"\temail = {email}",
    ]
    if signkey:
        lines.append(f"\tsigningkey = {signkey}")
        lines.append("[gpg]")
        lines.append("\tformat = ssh")
        lines.append("[commit]")
        lines.append("\tgpgsign = true")
        lines.append("[tag]")
        lines.append("\tgpgSign = true")
    lines.append("[init]")
    lines.append(f"\tdefaultBranch = {default_branch}")
    if profile == "work":
        lines.append("[jira]")
        lines.append("\tkeyPosition = suffix")
    return "\n".join(lines) + "\n"


def _confirm_overwrite(src: Path, profile: str) -> bool:
    print(f"Existing identity for '{profile}':")
    for line in src.read_text(encoding="utf-8").splitlines():
        print(f"  {line}")
    answer = input("Overwrite? [y/N]: ")
    return answer.lower() in {"y", "yes"}


def main(argv: list[str]) -> int:
    profile = parse_profile(argv)
    default_branch_default = PROFILE_DEFAULT_BRANCH[profile]

    repo_root = Path(__file__).resolve().parent.parent
    src = repo_root / "roles/devbox/local/.config/git" / f"identity-{profile}.gitconfig"
    src.parent.mkdir(parents=True, exist_ok=True)

    if src.is_file() and not _confirm_overwrite(src, profile):
        print("Kept existing.")
        return 0

    defaults = read_gitconfig_defaults(Path.home() / ".gitconfig")
    if defaults.get("default_branch"):
        default_branch_default = defaults["default_branch"]

    name = prompt_with_default(f"[{profile}] git user.name", defaults.get("name", ""))
    email = prompt_with_default(f"[{profile}] git user.email", defaults.get("email", ""))
    signkey = prompt_with_default(
        f"[{profile}] sign commits? SSH public-key path (empty = no signing)",
        defaults.get("signkey", ""),
    )
    default_branch = prompt_with_default(
        f"[{profile}] init.defaultBranch",
        default_branch_default,
    )

    content = render_identity(
        profile=profile,
        name=name,
        email=email,
        signkey=signkey,
        default_branch=default_branch,
    )
    src.write_text(content, encoding="utf-8")
    print(f"Wrote source: {src}")

    if os.environ.get("DEV") != "1":
        dst = Path.home() / ".config/git" / f"identity-{profile}.gitconfig"
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(src, dst)
        print(f"Applied: {dst}")

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv))
    except (EOFError, KeyboardInterrupt):
        # Non-interactive stdin closure or Ctrl-C — exit cleanly, no traceback.
        print("\nAborted.", file=sys.stderr)
        sys.exit(130)
