#!/usr/bin/env bash
# Generate a per-profile git identity into the (gitignored) local overlay and,
# unless DEV=1, apply it to the live ~/.config/git/ immediately.
#
# The identity is intentionally NOT stored in vault: it is regenerable in two
# prompts and the signing key it references is backed up separately. The local
# overlay is the source of truth (deployed by install_configs.yml Block 6); this
# script also copies straight to $HOME so a standalone `make git-identity` takes
# effect without a full playbook run.
#
# Usage: git-identity-gen.sh <personal|work>
set -euo pipefail

profile="${1:-}"
case "$profile" in
    personal|work) ;;
    *) echo "usage: git-identity-gen.sh <personal|work>" >&2; exit 2 ;;
esac

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src="$repo_root/roles/devbox/local/.config/git/identity-${profile}.gitconfig"
mkdir -p "$(dirname "$src")"

if [ -f "$src" ]; then
    echo "Existing identity for '$profile':"
    sed 's/^/  /' "$src"
    read -rp "Overwrite? [y/N]: " ans
    case "$ans" in y|Y|yes) ;; *) echo "Kept existing."; exit 0 ;; esac
fi

read -rp "[$profile] git user.name: " name
read -rp "[$profile] git user.email: " email
read -rp "[$profile] sign commits? SSH public-key path (empty = no signing): " signkey

{
    echo "# Generated by 'make git-identity' for the '$profile' profile."
    echo "# Local overlay — gitignored, per-machine. Regenerate with make git-identity."
    echo "[user]"
    echo "	name = $name"
    echo "	email = $email"
    if [ -n "$signkey" ]; then
        echo "	signingkey = $signkey"
        echo "[gpg]"
        echo "	format = ssh"
        echo "[commit]"
        echo "	gpgsign = true"
        echo "[tag]"
        echo "	gpgSign = true"
    fi
} > "$src"
echo "Wrote source: $src"

# Immediate apply to the live HOME, unless building the debug tree (dev_mode).
if [ "${DEV:-}" != "1" ]; then
    dst="$HOME/.config/git/identity-${profile}.gitconfig"
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "Applied: $dst"
fi
