---
- name: "Install Homebrew apps"
  community.general.homebrew:
    name: "{{ devbox_brew_secondary + devbox_extra_brew }}"
    state: "{{ 'latest' if upgrade_mode | default(false) | bool else 'present' }}"

- name: "Install Homebrew casks"
  community.general.homebrew_cask:
    name: "{{ devbox_brew_secondary_casks + devbox_extra_brew_casks }}"
    state: present
    install_options: 'adopt'
    upgrade_all: false
  register: cask_secondary_result
  failed_when:
    - cask_secondary_result.failed is defined
    - cask_secondary_result.failed
    - '"already installed" not in cask_secondary_result.msg'

- name: "Install npm packages"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: "{{ 'latest' if upgrade_mode | default(false) | bool else 'present' }}"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_facts['env']['PATH'] }}"
  loop: "{{ devbox_npm_packages }}"

- name: "Init Rust toolchain"
  ansible.builtin.command:
    cmd: rustup-init -y
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.cargo/bin/rustc"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_facts['env']['PATH'] }}"

- name: "Init OCaml (auto-setup writes shell hooks)"
  ansible.builtin.command:
    cmd: opam init -y -a
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.opam"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_facts['env']['PATH'] }}"

- name: "Install necessary OCaml packages"
  ansible.builtin.command:
    cmd: opam install -y ocaml-lsp-server odoc ocamlformat utop
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.opam/default/bin/utop"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_facts['env']['PATH'] }}"
    OPAMSWITCH: default

- name: "Install SWI-Prolog LSP server"
  ansible.builtin.command:
    cmd: swipl -g "pack_install(lsp_server, [interactive(false)])" -t halt
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/share/swi-prolog/pack/lsp_server"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_facts['env']['PATH'] }}"
