---
- name: "Install Homebrew apps"
  community.general.homebrew:
    name:
      - kitty
      - fish
      - fisher
      - bat
      - podman
      - mas
      - wget
      - curl
      - font-fira-code
      - htop
      - nvim
    state: present

- name: "Install Homebrew casks"
  community.general.homebrew_cask:
    name:
      - ghostty
      - font-ia-writer-duo
      - font-ia-writer-mono
      - font-ia-writer-quattro
      - font-meslo-for-powerlevel10k
      - font-meslo-for-powerline
      - font-meslo-lg
      - font-meslo-lg-dz
      - font-meslo-lg-nerd-font
    state: present

- name: "Regen fonts config"
  ansible.builtin.command:
    cmd: fc-cache -fv
