"""Tests for scripts/git-identity-gen.py.

The script has a Python-unfriendly filename (hyphens), so we load it as a module
via importlib rather than a plain import. Same shape as tests/git_hooks/, which
tests a hyphen-named artifact deployed verbatim.
"""

from __future__ import annotations

import importlib.util
import stat
import sys
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from types import ModuleType

SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "git-identity-gen.py"


def _load_module() -> ModuleType:
    spec = importlib.util.spec_from_file_location("git_identity_gen", SCRIPT)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


gid = _load_module()


# --- parse_profile ----------------------------------------------------------


@pytest.mark.parametrize("profile", ["personal", "work"])
def test_parse_profile_accepts_valid(profile: str) -> None:
    assert gid.parse_profile(["prog", profile]) == profile


@pytest.mark.parametrize(
    "argv",
    [
        ["prog"],
        ["prog", "nonsense"],
        ["prog", ""],
        ["prog", "PERSONAL"],  # case-sensitive, matches the bash `case` pattern
    ],
)
def test_parse_profile_rejects_invalid(
    argv: list[str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    with pytest.raises(SystemExit) as excinfo:
        gid.parse_profile(argv)
    assert excinfo.value.code == 2
    assert "usage:" in capsys.readouterr().err


# --- render_identity --------------------------------------------------------


def test_render_identity_personal_with_signkey() -> None:
    out = gid.render_identity(
        profile="personal",
        name="Alice Example",
        email="alice@example.com",
        signkey="~/.ssh/id_ed25519.pub",
        default_branch="master",
    )
    assert out == (
        "# Generated by 'make git-identity' for the 'personal' profile.\n"
        "# Local overlay — gitignored, per-machine. Regenerate with make git-identity.\n"
        "[user]\n"
        "\tname = Alice Example\n"
        "\temail = alice@example.com\n"
        "\tsigningkey = ~/.ssh/id_ed25519.pub\n"
        "[gpg]\n"
        "\tformat = ssh\n"
        "[commit]\n"
        "\tgpgsign = true\n"
        "[tag]\n"
        "\tgpgSign = true\n"
        "[init]\n"
        "\tdefaultBranch = master\n"
    )


def test_render_identity_work_without_signkey_adds_jira_suffix() -> None:
    out = gid.render_identity(
        profile="work",
        name="Bob Example",
        email="bob@corp.example",
        signkey="",
        default_branch="main",
    )
    assert "signingkey" not in out
    assert "[gpg]" not in out
    assert "[commit]" not in out
    assert "[tag]" not in out
    assert "[init]\n\tdefaultBranch = main\n" in out
    assert out.rstrip("\n").endswith("[jira]\n\tkeyPosition = suffix")


def test_render_identity_work_with_signkey_has_all_sections() -> None:
    out = gid.render_identity(
        profile="work",
        name="Bob Example",
        email="bob@corp.example",
        signkey="~/.ssh/work.pub",
        default_branch="develop",
    )
    for section in ["[user]", "[gpg]", "[commit]", "[tag]", "[init]", "[jira]"]:
        assert section in out
    assert "\tdefaultBranch = develop\n" in out
    assert "\tsigningkey = ~/.ssh/work.pub\n" in out
    assert "\tkeyPosition = suffix" in out


def test_render_identity_personal_never_emits_jira() -> None:
    out = gid.render_identity(
        profile="personal",
        name="A",
        email="a@b.c",
        signkey="",
        default_branch="master",
    )
    assert "[jira]" not in out
    assert "keyPosition" not in out


# --- read_gitconfig_defaults -----------------------------------------------


def test_read_gitconfig_defaults_missing_file(tmp_path: Path) -> None:
    assert gid.read_gitconfig_defaults(tmp_path / "nope") == {}


@pytest.mark.parametrize(
    ("gitconfig_body", "expected_name", "expected_email"),
    [
        # Unquoted (the natural git-emitted form).
        (
            "[user]\n\tname = Alice\n\temail = alice@example.com\n",
            "Alice",
            "alice@example.com",
        ),
        # Quoted (some setups leave literal quotes in the file — must be stripped).
        (
            '[user]\n\tname = "Alice"\n\temail = "alice@example.com"\n',
            "Alice",
            "alice@example.com",
        ),
        # Mixed: one quoted, one not.
        (
            '[user]\n\tname = "Alice"\n\temail = alice@example.com\n',
            "Alice",
            "alice@example.com",
        ),
    ],
)
def test_read_gitconfig_defaults_strips_quotes(
    tmp_path: Path,
    gitconfig_body: str,
    expected_name: str,
    expected_email: str,
) -> None:
    gitconfig = tmp_path / ".gitconfig"
    gitconfig.write_text(gitconfig_body, encoding="utf-8")
    defaults = gid.read_gitconfig_defaults(gitconfig)
    assert defaults["name"] == expected_name
    assert defaults["email"] == expected_email
    assert defaults["signkey"] == ""
    assert defaults["default_branch"] == ""


def test_read_gitconfig_defaults_full_content(tmp_path: Path) -> None:
    gitconfig = tmp_path / ".gitconfig"
    gitconfig.write_text(
        "[user]\n"
        "\tname = Alice\n"
        "\temail = alice@example.com\n"
        "\tsigningkey = ~/.ssh/id_ed25519.pub\n"
        "[init]\n"
        "\tdefaultBranch = trunk\n",
        encoding="utf-8",
    )
    defaults = gid.read_gitconfig_defaults(gitconfig)
    assert defaults == {
        "name": "Alice",
        "email": "alice@example.com",
        "signkey": "~/.ssh/id_ed25519.pub",
        "default_branch": "trunk",
    }


def test_strip_one_pair_of_quotes_only_strips_once() -> None:
    # Nested quotes: only the outer pair goes; the inner pair stays literal.
    # Bash: value=${x#\"}; value=${value%\"} — same semantics.
    assert gid.strip_one_pair_of_quotes('""Alice""') == '"Alice"'
    assert gid.strip_one_pair_of_quotes('"Alice') == "Alice"
    assert gid.strip_one_pair_of_quotes('Alice"') == "Alice"
    assert gid.strip_one_pair_of_quotes("Alice") == "Alice"
    assert gid.strip_one_pair_of_quotes("") == ""


# --- prompt_with_default ----------------------------------------------------


def test_prompt_with_default_empty_input_returns_default(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr("builtins.input", lambda _prompt="": "")
    assert gid.prompt_with_default("label", "the-default") == "the-default"


def test_prompt_with_default_nonempty_input_wins(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr("builtins.input", lambda _prompt="": "user-value")
    assert gid.prompt_with_default("label", "the-default") == "user-value"


def test_prompt_with_default_no_default_shows_bare_label(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    seen_prompts: list[str] = []

    def fake_input(prompt: str = "") -> str:
        seen_prompts.append(prompt)
        return "typed"

    monkeypatch.setattr("builtins.input", fake_input)
    assert gid.prompt_with_default("[personal] git user.name", "") == "typed"
    assert seen_prompts == ["[personal] git user.name: "]


def test_prompt_with_default_default_shown_in_brackets(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    seen_prompts: list[str] = []

    def fake_input(prompt: str = "") -> str:
        seen_prompts.append(prompt)
        return ""

    monkeypatch.setattr("builtins.input", fake_input)
    gid.prompt_with_default("label", "the-default")
    assert seen_prompts == ["label [the-default]: "]


# --- shebang / executability ------------------------------------------------


def test_script_has_python_shebang() -> None:
    assert SCRIPT.read_text(encoding="utf-8").startswith("#!/usr/bin/env python3")


def test_script_is_executable() -> None:
    assert SCRIPT.stat().st_mode & stat.S_IXUSR, "script must be executable"


# --- cleanup ----------------------------------------------------------------


def teardown_module() -> None:
    # The importlib load registers the module under a friendly name; drop it so
    # a subsequent import in the same session picks up on-disk changes.
    sys.modules.pop("git_identity_gen", None)
